### ISSUE TITLE
K8s jobs and private registries

### ISSUE THREAD

**Issue by robmaxwellirl** [actions/runner-container-hooks#24]
Hello,

I've recently updated to ARC v0.25.x and it's supported use of container registries as jobs within it.
I had posted the query initially within the [ARC discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions/1658), but believe it to be an issue with the k8s hooks that are a part of the container build for the latest release.

When testing with the private repository, I do not see a secret created in the same space as the runner is set, and the workflow job ends up in an Image pull error loop.

Looking at the [source code](https://github.com/actions/runner-container-hooks/blob/e2033b29c76a6fd8cb23f25d00ad199858ba70ab/packages/k8s/src/k8s/index.ts#L96-L104) it looks as though it should create an imageSecret to be used for the pull from the private registry but this fails to work.

I'm not too familiar with the typescript language, so not sure how to troubleshoot it, but happy to with some guidance.
I've tried to populate a registry component in the action YAML, but this fails to run as it's not valid YAML in various places.

The runner [prepare-job.json file ](https://github.com/actions/runner-container-hooks/blob/e2033b29c76a6fd8cb23f25d00ad199858ba70ab/examples/prepare-job.json#L62-L66) suggests that it's expecting registry elements, but can't get past the action YAML validation with it.

Any help appreciated.

**Comment by nikola-jokic** [comment]
Hi @robmaxwellirl,

Thank you for reporting it! I will try to reproduce this issue and get back to you as soon as I can
