### ISSUE TITLE
Should not override default service entry point in k8s hooks

### ISSUE THREAD

**Issue by carlturnerfs** [actions/runner-container-hooks#44]
[Currently](https://github.com/actions/runner-container-hooks/blob/d988d965c57642f972246e28567301f6b4c054e1/packages/k8s/src/hooks/prepare-job.ts#L161), the `createPodSpec` method for preparing jobs sets a default entry point of `tail -f /dev/null` whenever the `entryPoint` parameter is not set by the runner. There is actually no such parameter in the [definition](https://github.com/actions/runner/blob/main/docs/adrs/1891-container-hooks.md#prepare_job-hook) of the prepare job hook. (`createOptions`, on the other hand, can be passed through, but is ignored.) So all containers are executed with this default entry point.

But this means in particular containers for services are started with this no-op entry point, rather than their default (usually very sensible) entry point and there is no way to override this from the workflow definition! Therefore it doesn't seem possible to use a postgres service container.

It would seem sensible not to override the entry point of these containers, since (at least in the case of examples like postgres) they have entirely sensible defaults built into the container. (Ideally there would be a proper way to set the entry point for services explicitly in the workflow definition, but that's been [an outstanding issue](https://github.com/orgs/community/discussions/26688) for a long time now.)

This would also bring the behaviour in line with the standard GitHub runner, which uses the default entry point of the container (unless `createOptions` contains an `--entrypoint` switch).

**Comment by nikola-jokic** [comment]
Hey @carlturnerfs,

Thank you for raising this issue and this great explanation! We will fix this as soon as we can :relaxed:
