### ISSUE TITLE
Jobs fail when services are defined without ports

### ISSUE THREAD

**Issue by claveaur** [actions/runner-container-hooks#54]
Hi team,

After adding changes from #53, the runner start correctly with services when there is a port defined but not without any port.

Job [ok](https://github.com/claveaur/test-runner-k8s/actions/runs/3841041260) with following [workflow](https://github.com/claveaur/test-runner-k8s/blob/8f462994a7e2944a8767d24637adcac2c37f6f5a/.github/workflows/test-workflow.yaml)

Job [ko](https://github.com/claveaur/test-runner-k8s/actions/runs/3841050925) with following [workflow](https://github.com/claveaur/test-runner-k8s/blob/1e10075458b4204bc127605414dbebe17153a3ea/.github/workflows/test-workflow.yaml)

Traces : 

```
##[debug]Job pod is ready for traffic
##[debug]Setting isAlpine to true
Error: Object reference not set to an instance of an object.
##[debug]System.NullReferenceException: Object reference not set to an instance of an object.
##[debug]   at GitHub.Runner.Worker.Container.ContainerHooks.ContainerHookManager.UpdateJobContext(IExecutionContext context, ContainerInfo jobContainer, List`1 serviceContainers, PrepareJobResponse response)
##[debug]   at GitHub.Runner.Worker.Container.ContainerHooks.ContainerHookManager.PrepareJobAsync(IExecutionContext context, List`1 containers)
##[debug]   at GitHub.Runner.Worker.ContainerOperationProvider.StartContainersAsync(IExecutionContext executionContext, Object data)
##[debug]   at GitHub.Runner.Worker.JobExtensionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Initialize containers
```

**Comment by nikola-jokic** [comment]
Thanks! I will work on the fix today :relaxed:

**Comment by nikola-jokic** [comment]
Do you want to make a PR? :relaxed:
And if you want, please add tests

Unfortunately, I can't see the workflow (probably a private repo)

**Comment by claveaur** [comment]
> Unfortunately, I can't see the workflow (probably a private repo)

Oh sorry I changed it to public 👍

**Comment by claveaur** [comment]
I opened the PR @nikola-jokic, do not hesitate to reach me for it 😉
