### ISSUE TITLE
runner-container-hooks doesn't handle shared-workflow (actions/checkout@v3)

### ISSUE THREAD

**Issue by abdulari** [actions/runner-container-hooks#86]
Hi.
I'm creating a new package for another container runtime. I can't disclose which container runtime is due to legal reasons.
we've written runner-container-hooks for that runtime, and it manages to spawn and destroy the container successfully.

the problem we're facing is when the workflow use shared-workflow.
in this picture, we're using actions/checkout@v3, and the container we've spawn does not have proper application installed for this action to run.
from what I understand, actions/checkout@v3 are required to run on a different container (node16).

I am expecting that runner-container-hooks will get comand=prepare_job AND command=run_script_step. But from my debugging, I only receive command=run_script_step

any advice on what I can do here? 
I should be able to start a secondary container if I can detect which container the shared-workflow wants to use

![image](https://github.com/actions/runner-container-hooks/assets/20963760/439f35cf-6539-43d7-b9cc-e344deb0451f)

**Comment by abdulari** [comment]
oh wow, this is useful information.
it does makes sense that `checkout` step should only trigger `run_script_step` 👍 
it also means that we can check what the step is trying to do, and choose which container we want to run it on. 
wonderful. 😄  

I think we can run a few additional steps to start containers to run `checkout` if we can detect them.
any suggestion/documentation on hooks/API that can help us to detect what workflow is trying to run?
we can git clone those actions in a temp directory and scan for action.yml

![image](https://github.com/actions/runner-container-hooks/assets/20963760/c69e04bd-5673-4aa4-b375-dbebad50839f)

**Comment by nikola-jokic** [comment]
The runner already downloads the action that needs to be executed so you can avoid the git clone :relaxed:.

![image](https://github.com/actions/runner-container-hooks/assets/97525037/589f8cf7-87f1-4c15-b33d-dbe17cbbd264)
The entrypoint can inform you what type of actions is it based on the executable it needs to run (node, bash, ...), and the entrypoint argument is the directory where the action is stored. So you can distinguish between a step that is trying to execute the action (it will have a script at the path starting with `/__w/_actions`), and the job step (`/__w/_temp/...`)

**Comment by abdulari** [comment]
wonderful. I think we got all the information that we need.
thanks for your time 😄
